# Maximum size of a party
max-size: 4

# How long an invitation lasts in seconds
# before it is automatically cancelled
invite-timeout: 30

# Whether to remove players
# when they disconnect
remove-on-dc: false

# Whether to assign a new party leader
# when the current one disconnects
new-leader-on-dc: true

# Whether members of the same party can hurt each other
friendly-fire: true

# Whether party members are considered allies in Fabled
party-ally: true

# Whether to use the scoreboard for
# displaying party information
use-scoreboard: false

# Whether only the leader of a party
# can invite new members
only-leader-invites: true

# Whether levels are shown in the scoreboard over health
level-scoreboard: false

# Modifications to experience gained
exp-modifications:

  # Maximum distance between party members for the exp sharing to take effect, in blocks
  # Set to 0 to disable exp sharing, or -1 to enable regardless of distance
  radius: 0

  # Modifier for the number of members
  # normally ranging from 0 to 1
  # 0 -> Full experience for all members
  # 1 -> Evenly split experience
  members: 1.0

  # Modifier for the difference in level
  # between party members
  # Generally should be small decimals
  # (0 - 0.01 is a good range)
  # 0 -> No change in experience
  level: 0.0

sharing:
  # The type of item sharing to use.
  # Ignores items dropped by players and from blocks, to avoid duplication
  # none -> Disables item sharing
  # sequential -> Members of the party take turns getting items, in a per-unit basis
  # random -> Each picked up item unit is granted to a random party member
  # sequential-stack -> Members of the party take turns getting items, in a per-stack basis
  # random-stack -> Each picked up item stack is granted to a random party member
  type: none

  # Maximum distance between party members for the item sharing to take effect, in blocks
  # Set to -1 to enable regardless of distance
  radius: 0

# Whether debug messages are enabled
debug-messages: false